/* Forge Gym: PWA senza server, dati memorizzati esclusivamente sul dispositivo. */
(()=>{'use strict';
const {catalog,first,second}=ForgeSeed;
const C=ForgeCore;
const KEY='forge-gym-data-v1';
const uid=()=>('id-'+(globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const imgSrc=s=>{s=String(s||'');return /^(\.\/assets\/exercises\/[\w-]+\.webp|https:\/\/[^\s]+|data:image\/(?:png|jpeg|webp);base64,[\w+/=]+)$/.test(s)?esc(s):'';};
const pict=(ex,extra='')=>ex.image&&imgSrc(ex.image)?`<img class="thumb ${extra}" src="${imgSrc(ex.image)}" alt="Illustrazione: ${esc(ex.name)}" loading="lazy">`:`<div class="thumb thumb-placeholder ${extra}" aria-hidden="true">◈</div>`;
function cloneExercise(key){const d=catalog[key];return {id:uid(),...structuredClone(d)};}
function defaultDb(){return {version:1,plans:[{id:uid(),name:'Giorno 1',description:'Prima giornata della scheda • Full Body 2x',exercises:first.map(cloneExercise)},{id:uid(),name:'Giorno 2',description:'Seconda giornata della scheda • Full Body 2x',exercises:second.map(cloneExercise)}],history:[],active:null};}
function load(){try{const val=JSON.parse(localStorage.getItem(KEY)||'null');if(val&&val.version===1&&Array.isArray(val.plans)&&Array.isArray(val.history))return val;}catch(e){console.error('Backup locale non leggibile:',e);}return defaultDb();}
let db=load();
let ui={page:db.active?'session':'home',planId:db.plans[0]?.id||'',historyId:'',exerciseKey:'',openExerciseId:null,modal:'',pendingImage:'',restUntil:0,progressMetric:'volume',historyFilter:'all',showAllExercises:false};
const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(db));return true;}catch(err){console.error(err);toast('Memoria piena: esporta un backup e libera spazio.');return false;}};
persist();
const plan=id=>db.plans.find(p=>p.id===id);
const countDone=()=>db.active?.entries?.reduce((n,e)=>n+(e.kind==='strength'?C.setsDone(e).length:e.done?1:0),0)||0;
const countTarget=()=>db.active?.entries?.reduce((n,e)=>n+(e.kind==='strength'?e.sets.length:1),0)||0;
const shortDate=date=>new Date(date).toLocaleDateString('it-IT',{day:'2-digit',month:'short',year:'numeric'});
const timeStamp=date=>new Date(date).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit'});
const labelSeries=ex=>ex.kind==='strength'?ex.sets.map(s=>`${s.min}-${s.max}`).join(' · '):ex.kind==='time'?`${ex.minutes||8} min`:'Mobilità';
const nav=(id,emoji,label,active)=>`<button class="nav-btn ${active?'active':''}" data-action="navigate" data-page="${id}" aria-label="${label}" ${active?'aria-current="page"':''}><span class="nav-icon">${emoji}</span>${label}</button>`;
function shell(content){let current=ui.page;document.getElementById('app').innerHTML=`<div class="app-shell">
<header class="topbar"><div class="brand"><div class="brand-mark">F</div><div><strong>FORGE GYM</strong><small>TRAINING JOURNAL</small></div></div><button class="top-icon" data-action="navigate" data-page="settings" aria-label="Impostazioni">⚙</button></header>
${db.active&&current!=='session'?`<div class="floating-session"><span style="font-size:20px">●</span><div class="grow"><strong class="small">Allenamento in corso</strong><div class="tiny muted">${esc(db.active.planName)} · ${countDone()}/${countTarget()} attività / serie</div></div><button class="btn btn-primary btn-sm" data-action="navigate" data-page="session">Riprendi ↗</button></div>`:''}
<main id="main-content">${content}</main></div>
<nav class="bottom-nav" aria-label="Menu principale">${nav('home','⌂','Home',current==='home')}${nav('plans','▤','Schede',current==='plans'||current==='plan')}${nav('history','◷','Storico',current==='history'||current==='history-detail')}${nav('progress','▥','Progressi',current==='progress'||current==='exercise-progress')}</nav>`;
renderModal();updateTimer();}
function render(){let content='';switch(ui.page){case 'home':content=home();break;case 'plans':content=plans();break;case 'plan':content=planPage();break;case 'session':content=sessionPage();break;case 'history':content=historyPage();break;case 'history-detail':content=historyDetail();break;case 'progress':content=progressPage();break;case 'exercise-progress':content=exerciseProgress();break;case 'settings':content=settingsPage();break;default:ui.page='home';content=home();}
shell(content);}
function toast(message){const el=document.getElementById('toast-root');if(!el)return;el.innerHTML=`<div class="toast">${esc(message)}</div>`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>{el.innerHTML='';},3000);}
function stat(label,value,suffix=''){return `<div class="stat"><div class="stat-label">${esc(label)}</div><div class="stat-number">${esc(value)}<span class="stat-suffix">${esc(suffix)}</span></div></div>`;}
function home(){const st=C.stats(db.history);const weeks=C.weekData(db.history);const recent=db.history.slice(-3).reverse();const rplans=db.plans.slice(0,3);
return `<p class="eyebrow">IL TUO SPAZIO</p><h1 class="page-title">Diventa più forte.<br><span style="color:var(--accent)">Una serie alla volta.</span></h1><p class="subtitle">Le tue schede, i carichi e i progressi. Tutto in un unico posto.</p>
<div class="hero"><span class="badge">${db.active?'● SEDUTA IN CORSO':'PRONTO AD ALLENARTI'}</span><h2 style="margin-top:13px">${db.active?'Continua da dove eri rimasto.':'Il prossimo allenamento ti aspetta.'}</h2><p>${db.active?esc(db.active.planName)+' — i dati si salvano dopo ogni modifica.':'Scegli una scheda e registra ogni serie in pochi tocchi.'}</p>
<button class="btn btn-primary" data-action="${db.active?'navigate':'start'}" ${db.active?'data-page="session"':`data-id="${esc(db.plans[0]?.id||'')}"`}>${db.active?'Riprendi la seduta →':'Inizia allenamento →'}</button></div>
<div class="section-head"><h2 class="section-title">A colpo d’occhio</h2><span class="tiny muted">Tutti i tempi</span></div><div class="stats-grid">${stat('Sedute completate',st.sessions)}${stat('Serie registrate',st.sets)}${stat('Volume sollevato',C.fmt(st.volume),'kg')}${stat('Esercizi svolti',st.exerciseCount)}</div>
<div class="section-head"><h2 class="section-title">Le tue schede</h2><button data-action="navigate" data-page="plans">Vedi tutte →</button></div><div class="stack">${rplans.map(p=>`<div class="card plan-card"><div class="plan-icon">${esc(p.name.match(/\d+/)?.[0]||'✦')}</div><div class="grow"><div class="plan-title">${esc(p.name)}</div><div class="plan-sub">${p.exercises.length} esercizi · ${esc(p.description||'La tua scheda')}</div></div><button class="icon-button" data-action="go-plan" data-id="${esc(p.id)}" aria-label="Apri ${esc(p.name)}">→</button></div>`).join('')||empty('Non ci sono schede. Creane una per iniziare.')}</div>
<div class="section-head"><h2 class="section-title">Ultime 6 settimane</h2><button data-action="navigate" data-page="progress">Statistiche →</button></div><div class="card chart-panel">${chartBars(weeks,'sessions')}<div class="chart-note">Numero di allenamenti completati per settimana</div></div>
<div class="section-head"><h2 class="section-title">Ultime sessioni</h2></div>${recent.length?`<div class="stack">${recent.map(historyItem).join('')}</div>`:empty('Le prime statistiche appariranno dopo la tua prima seduta.')}`;
}
function empty(txt){return `<div class="empty"><div class="empty-icon">✳</div>${esc(txt)}</div>`;}
function plans(){return `<p class="eyebrow">PROGRAMMA PERSONALE</p><h1 class="page-title">Le tue schede.</h1><p class="subtitle">Modifica i due giorni originali oppure crea programmi nuovi.</p>
<div class="stack">${db.plans.map((p,i)=>`<div class="card plan-card"><div class="plan-icon">${i+1}</div><div class="grow"><div class="plan-title">${esc(p.name)}</div><div class="plan-sub">${p.exercises.length} esercizi · ${p.exercises.filter(e=>e.kind==='strength').reduce((a,e)=>a+e.sets.length,0)} serie di forza</div></div><button class="btn btn-outline btn-sm" data-action="go-plan" data-id="${esc(p.id)}">Apri ↗</button></div>`).join('')||empty('Crea una scheda per cominciare.')}</div>
<div style="margin-top:15px"><button class="btn btn-primary btn-full" data-action="create-plan-modal">＋ Nuova scheda</button></div><p class="footnote">Le modifiche alle schede non cambiano le sessioni già archiviate nello storico.</p>`;}
function planPage(){const p=plan(ui.planId);if(!p){ui.page='plans';return plans();}
return `<div class="row spaced"><p class="eyebrow">PROGRAMMA DI ALLENAMENTO</p><button class="btn-link" data-action="navigate" data-page="plans">← Tutte</button></div><h1 class="page-title">${esc(p.name)}</h1><p class="subtitle">${esc(p.description||'Scheda personalizzata')} · ${p.exercises.length} esercizi</p>
<div class="row" style="margin-bottom:18px"><button class="btn btn-primary grow" data-action="start" data-id="${esc(p.id)}" ${db.active?'disabled title="Termina la seduta attiva prima di iniziarne una nuova"':''}>▶ Inizia questa scheda</button><button class="btn btn-outline" data-action="edit-plan-modal" data-id="${esc(p.id)}">✎</button></div>
<div class="section-head"><h2 class="section-title">Esercizi</h2><span class="tiny muted">In ordine di esecuzione</span></div>
<div class="stack">${p.exercises.map((e,i)=>`<div class="plan-list-item">${pict(e)}<div class="grow"><div class="tiny muted">${i+1} · ${esc(e.group)}</div><div class="bold small" style="margin:3px 0">${esc(e.name)}</div><div class="tiny muted">${esc(labelSeries(e))} ${e.rest?'· recupero '+(e.rest/60)+' min':''}</div></div><div style="display:grid;gap:5px"><button class="icon-button" data-action="move-ex" data-id="${esc(e.id)}" data-dir="-1" aria-label="Sposta su" ${i===0?'disabled':''}>↑</button><button class="icon-button" data-action="move-ex" data-id="${esc(e.id)}" data-dir="1" aria-label="Sposta giù" ${i===p.exercises.length-1?'disabled':''}>↓</button></div><button class="icon-button" data-action="edit-ex-modal" data-id="${esc(e.id)}" aria-label="Modifica esercizio">✎</button></div>`).join('')||empty('Nessun esercizio presente.')}</div>
<div class="row" style="margin-top:15px"><button class="btn btn-primary grow" data-action="library-modal">＋ Aggiungi esercizio</button><button class="btn btn-outline" data-action="custom-ex-modal">Personalizzato</button></div>
<div class="divider"></div><div class="row"><button class="btn btn-outline grow" data-action="duplicate-plan" data-id="${esc(p.id)}">⧉ Duplica scheda</button><button class="btn btn-danger" data-action="delete-plan" data-id="${esc(p.id)}">Elimina</button></div>`;}
function start(id){if(db.active){toast('Completa o annulla prima la seduta in corso.');return;}const p=plan(id);if(!p)return;
const entries=p.exercises.map(ex=>{const last=C.lastExercise(db.history,C.exerciseKey(ex));return {...structuredClone(ex),exerciseId:ex.id,sets:ex.sets.map((s,i)=>({...s,id:uid(),reps:s.min,kg:Number(last?.sets?.[i]?.kg)||0,done:false})),done:false};});
db.active={id:uid(),planId:p.id,planName:p.name,startedAt:new Date().toISOString(),entries};ui.restUntil=0;ui.openExerciseId=entries[0]?.id||null;ui.page='session';persist();render();window.scrollTo(0,0);}
function sessionPage(){const s=db.active;if(!s)return `<p class="eyebrow">ALLENAMENTO</p><h1 class="page-title">Nessuna seduta attiva.</h1><button class="btn btn-primary" data-action="navigate" data-page="plans">Vai alle schede</button>`;
const all=countTarget(),done=countDone(),pct=all?Math.round(done/all*100):0;
return `<div class="workout-head"><p class="eyebrow">● ALLENAMENTO IN CORSO</p><button class="btn btn-outline btn-sm" data-action="cancel-session">Annulla</button></div><h1 class="page-title">${esc(s.planName)}</h1><p class="subtitle">Inizio alle ${timeStamp(s.startedAt)} · ${s.entries.length} esercizi · salvataggio automatico</p>
<div id="timer-banner" class="timer-banner hidden"><span>⏱ Recupero: <span id="timer-count">0:00</span></span><button data-action="stop-timer">Salta</button></div>
<div class="card" style="margin-bottom:16px"><div class="row spaced"><strong>${done} / ${all} completati</strong><span class="badge">${pct}%</span></div><div class="progress-track" style="margin-top:12px"><div class="progress-fill" style="width:${pct}%"></div></div></div>
<div class="stack">${s.entries.map((e,i)=>workoutExercise(e,i)).join('')}</div><div class="card" style="margin-top:20px;background:#243328;border-color:#4a6344"><div class="row spaced"><div><div class="bold">Hai finito?</div><div class="tiny muted" style="margin-top:5px">Puoi salvare anche una seduta parziale.</div></div><span class="badge">${pct}%</span></div><button class="btn btn-primary btn-full" style="margin-top:14px" data-action="finish">✓ Salva e termina seduta</button></div>
<p class="footnote">Le serie sono registrate soltanto quando premi “✓ Fatto”. I kg dei manubri sono per singolo manubrio; il volume totale li conta entrambi.</p>`;
}
function workoutExercise(e,i){const done=e.kind==='strength'?C.setsDone(e).length:e.done?1:0;const total=e.kind==='strength'?e.sets.length:1;const open=ui.openExerciseId===e.id;const rec=C.recommendation(e,db.history);
return `<article class="card exercise-card" id="ex-${esc(e.id)}"><button class="exercise-main" data-action="toggle-ex" data-id="${esc(e.id)}" aria-expanded="${open?'true':'false'}">${pict(e)}<div class="grow"><div class="exercise-num">${String(i+1).padStart(2,'0')} · ${esc(e.group)}</div><div class="exercise-title">${esc(e.name)}</div><div class="exercise-meta">${esc(labelSeries(e))} · ${done}/${total} completati</div><div class="progress-track progress-small" style="margin-top:7px"><div class="progress-fill" style="width:${Math.round(done/total*100)}%"></div></div></div><span class="arrow ${open?'rotate':''}">⌄</span></button>
${open?`<div class="exercise-expanded"><p class="exercise-description">${esc(e.description||'Regola la macchina, mantieni la postura e scegli un carico gestibile.')}</p>
${e.kind==='strength'?`${rec.type!=='none'&&db.history.length?`<div class="recommendation ${rec.type==='hold'?'warn':''}"><div class="grow"><p><strong>${rec.type==='increase'?'↗ Progressione suggerita: ':rec.type==='first'?'Primo allenamento: ':'Obiettivo: '}</strong>${esc(rec.text)}</p></div>${rec.type==='increase'?`<button class="btn btn-primary btn-sm" data-action="apply-step" data-id="${esc(e.id)}">Applica</button>`:''}</div>`:''}
<div class="progress-pills"><span class="progress-pill">${e.sets.length} serie</span><span class="progress-pill">Recupero ${e.rest?e.rest/60+' min':'libero'}</span><span class="progress-pill">${esc(e.loadLabel||'kg')}</span></div>
${e.sets.map((set,idx)=>setRow(e,set,idx)).join('')}`:`<div class="activity-row"><div><strong>${e.kind==='time'?'Minuti':'Attività'}</strong><div class="tiny muted">${e.kind==='time'?'Durata pianificata: '+(e.minutes||8)+' min':'Segna quando hai completato'}</div></div>${e.kind==='time'?`<input aria-label="Minuti effettivi" type="number" min="0" max="600" step="1" value="${Number(e.minutes)||8}" data-field="minutes" data-eid="${esc(e.id)}">`:''}<button class="done-toggle ${e.done?'is-done':''}" data-action="activity-done" data-id="${esc(e.id)}">${e.done?'✓ Fatto':'○ Fatto'}</button></div>`}
${e.kind==='strength'?`<button class="btn-link" data-action="exercise-insights" data-key="${esc(e.key)}">Vedi storico e progressi →</button>`:''}</div>`:''}</article>`;}
function setRow(e,s,i){const base=Number(s.min)||6;const options=[...new Set([base,Number(s.max)||base+2,(Number(s.max)||base+2)+2,Number(s.reps)])].filter(n=>n>=0).sort((a,b)=>a-b);
return `<div class="set-row ${s.done?'completed':''}"><div class="set-head"><div><strong>SERIE ${i+1}</strong><small>Target ${s.min}–${s.max}</small></div><button class="done-toggle ${s.done?'is-done':''}" data-action="set-done" data-eid="${esc(e.id)}" data-index="${i}">${s.done?'✓ Fatto':'○ Fatto'}</button></div>
<div class="set-inputs"><div><div class="field-caption">Ripetizioni fatte</div><div class="rep-buttons">${options.map(n=>`<button class="rep-btn ${Number(s.reps)===n?'selected':''}" data-action="set-reps" data-eid="${esc(e.id)}" data-index="${i}" data-value="${n}">${n}</button>`).join('')}</div></div>
<div><div class="field-caption">${esc(e.loadLabel||'kg')} utilizzati</div><div class="weight-controls"><button data-action="weight-step" data-eid="${esc(e.id)}" data-index="${i}" data-dir="-1" aria-label="Diminuisci peso">−</button><input type="number" inputmode="decimal" min="0" max="2000" step="0.5" aria-label="Carico serie ${i+1} in ${esc(e.loadLabel||'kg')}" data-field="kg" data-eid="${esc(e.id)}" data-index="${i}" value="${s.kg||0}"><button data-action="weight-step" data-eid="${esc(e.id)}" data-index="${i}" data-dir="1" aria-label="Aumenta peso">＋</button></div></div></div></div>`;}
function finish(){if(!db.active)return;if(countDone()===0){toast('Segna almeno una serie o attività prima di salvare.');return;}const s=db.active;db.history.push({...structuredClone(s),endedAt:new Date().toISOString()});db.active=null;ui.restUntil=0;ui.page='history';ui.historyId=s.id;persist();render();window.scrollTo(0,0);toast('Seduta salvata! Ottimo lavoro.');}
function historyItem(h){const st=(h.entries||[]).reduce((n,e)=>n+(e.kind==='strength'?C.setsDone(e).length:e.done?1:0),0);const d=new Date(h.endedAt||h.startedAt);return `<div class="card history-card"><div class="history-date"><b>${d.getDate()}</b><span>${d.toLocaleDateString('it-IT',{month:'short'})}</span></div><div class="grow"><div class="bold small">${esc(h.planName)}</div><div class="tiny muted">${st} serie/attività · ${C.fmt((h.entries||[]).reduce((v,e)=>v+C.volume(e),0))} kg di volume</div></div><button class="icon-button" data-action="history-detail" data-id="${esc(h.id)}" aria-label="Dettagli sessione">→</button></div>`;}
function historyPage(){const filters=['all',...new Set(db.history.map(h=>h.planName))];const list=db.history.filter(h=>ui.historyFilter==='all'||h.planName===ui.historyFilter).slice().reverse();return `<p class="eyebrow">DIARIO PERSONALE</p><h1 class="page-title">Il tuo storico.</h1><p class="subtitle">Ogni serie resta registrata, anche se modifichi le schede.</p><div class="filter-row">${filters.map(f=>`<button class="chip ${ui.historyFilter===f?'active':''}" data-action="history-filter" data-value="${esc(f)}">${esc(f==='all'?'Tutte le sedute':f)}</button>`).join('')}</div><div class="stack" style="margin-top:12px">${list.map(historyItem).join('')||empty('Nessuna seduta ancora registrata.')}</div>`;}
function historyDetail(){const h=db.history.find(h=>h.id===ui.historyId);if(!h)return historyPage();const completed=(h.entries||[]).filter(e=>e.kind==='strength'?C.setsDone(e).length:e.done);
return `<div class="row spaced"><p class="eyebrow">DETTAGLIO SEDUTA</p><button class="btn-link" data-action="navigate" data-page="history">← Storico</button></div><h1 class="page-title">${esc(h.planName)}</h1><p class="subtitle">${shortDate(h.startedAt)} · ${timeStamp(h.startedAt)}–${timeStamp(h.endedAt)}</p><div class="stats-grid">${stat('Serie completate',completed.reduce((a,e)=>a+(e.kind==='strength'?C.setsDone(e).length:1),0))}${stat('Volume totale',C.fmt(completed.reduce((a,e)=>a+C.volume(e),0)),'kg')}</div>
<div class="section-head"><h2 class="section-title">Esercizi registrati</h2></div><div class="stack">${completed.map(e=>`<div class="card"><div class="row">${pict(e,'thumb-sm')}<div class="grow"><div class="bold small">${esc(e.name)}</div><div class="tiny muted">${esc(e.group)}</div></div></div><div class="divider"></div>${e.kind==='strength'?`<div class="mini-list">${C.setsDone(e).map((s,i)=>`<div class="row spaced small"><span class="muted">Serie ${i+1}</span><strong>${s.reps} rip. × ${C.fmt(s.kg)} ${esc(e.loadLabel||'kg')}</strong></div>`).join('')}</div>`:`<div class="small">✓ Completato ${e.kind==='time'?'· '+e.minutes+' minuti':''}</div>`}</div>`).join('')}</div><div class="divider"></div><button class="btn btn-danger btn-full" data-action="delete-history" data-id="${esc(h.id)}">Elimina questa seduta</button>`;}
function chartBars(weeks,metric){let max=Math.max(1,...weeks.map(w=>w[metric]));const W=340,H=142,baseline=114,bw=35,gap=19;return `<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Grafico di ${metric==='volume'?'volume':'sedute'} nelle ultime 6 settimane"><line x1="5" y1="${baseline}" x2="335" y2="${baseline}" stroke="#45534a" stroke-width="1"/>${weeks.map((w,i)=>{const height=(w[metric]/max)*87,x=12+i*(bw+gap);return `<rect x="${x}" y="${baseline-height}" width="${bw}" height="${height}" rx="7" fill="${i===weeks.length-1?'#c9fb75':'#5b7955'}"/><text x="${x+bw/2}" y="${Math.max(15,baseline-height-7)}" fill="#c9fb75" font-size="10" text-anchor="middle">${metric==='volume'&&w[metric]>=1000?Math.round(w[metric]/1000)+'k':Math.round(w[metric])}</text><text x="${x+bw/2}" y="134" class="chart-label" text-anchor="middle">${esc(w.label)}</text>`;}).join('')}</svg>`;}
function chartLine(items){const valid=items.slice(-9);if(!valid.length)return empty('Nessun dato disponibile per questo esercizio.');const W=340,H=166;let max=Math.max(1,...valid.map(x=>x.weight));const y=n=>133-(n/max)*108;const x=i=>valid.length===1?170:26+(i/(valid.length-1))*287;return `<svg class="chart" viewBox="0 0 ${W} ${H}" role="img" aria-label="Andamento massimo carico per seduta"><line x1="15" y1="133" x2="325" y2="133" stroke="#4f6154" stroke-dasharray="4 4"/><line x1="15" y1="79" x2="325" y2="79" stroke="#324038" stroke-dasharray="4 4"/><polyline fill="none" stroke="#c9fb75" stroke-width="3" stroke-linejoin="round" stroke-linecap="round" points="${valid.map((v,i)=>`${x(i)},${y(v.weight)}`).join(' ')}"/>${valid.map((v,i)=>`<circle cx="${x(i)}" cy="${y(v.weight)}" r="5" fill="#c9fb75" stroke="#0c100f" stroke-width="2"/><text x="${x(i)}" y="${Math.max(12,y(v.weight)-11)}" fill="#d6f7ad" font-size="11" text-anchor="middle">${C.fmt(v.weight)}</text><text x="${x(i)}" y="156" class="chart-label" text-anchor="middle">${new Date(v.date).toLocaleDateString('it-IT',{day:'numeric',month:'numeric'})}</text>`).join('')}</svg>`;}
function uniqueExercises(){const seen=new Set();return db.plans.flatMap(p=>p.exercises).concat(db.history.flatMap(h=>h.entries||[])).filter(e=>{const k=C.exerciseKey(e);if(e.kind!=='strength'||seen.has(k))return false;seen.add(k);return true;});}
function progressPage(){const st=C.stats(db.history);const weeks=C.weekData(db.history);const all=uniqueExercises();const ranked=all.map(e=>({e,series:C.series(db.history,C.exerciseKey(e))})).sort((a,b)=>b.series.length-a.series.length);const shown=ui.showAllExercises?ranked:ranked.slice(0,8);
return `<p class="eyebrow">ALLENAMENTO INTELLIGENTE</p><h1 class="page-title">I tuoi progressi.</h1><p class="subtitle">Numeri reali e suggerimenti semplici per il sovraccarico progressivo.</p><div class="stats-grid">${stat('Sedute',st.sessions)}${stat('Serie eseguite',st.sets)}${stat('Volume totale',C.fmt(st.volume),'kg')}${stat('Esercizi fatti',st.exerciseCount)}</div>
<div class="section-head"><h2 class="section-title">Trend settimanale</h2></div><div class="card chart-panel"><div class="filter-row"><button class="chip ${ui.progressMetric==='volume'?'active':''}" data-action="progress-metric" data-value="volume">Volume kg</button><button class="chip ${ui.progressMetric==='sessions'?'active':''}" data-action="progress-metric" data-value="sessions">Sedute</button></div>${chartBars(weeks,ui.progressMetric)}<div class="chart-note">${ui.progressMetric==='volume'?'Somma kg × ripetizioni delle serie segnate come fatte':'Sedute concluse per settimana'}</div></div>
<div class="section-head"><h2 class="section-title">Per esercizio</h2><span class="tiny muted">${all.length} esercizi</span></div><div class="stack">${shown.map(({e,series})=>{const last=series.at(-1);const first=series[0];const change=last&&first&&series.length>1?last.weight-first.weight:null;return `<div class="card plan-card">${pict(e,'thumb-sm')}<div class="grow"><div class="bold small">${esc(e.name)}</div><div class="tiny muted">${last?`Ultimo carico max ${C.fmt(last.weight)} ${esc(e.loadLabel||'kg')}`:'Non ancora registrato'}</div>${change!==null?`<div class="tiny" style="color:${change>=0?'var(--accent)':'var(--orange)'}">${change>=0?'+':''}${C.fmt(change)} kg rispetto alla prima seduta</div>`:''}</div><button class="icon-button" data-action="exercise-insights" data-key="${esc(C.exerciseKey(e))}">→</button></div>`;}).join('')||empty('Aggiungi esercizi a una scheda per vederli qui.')}</div>${ranked.length>8?`<button class="btn btn-outline btn-full" style="margin-top:12px" data-action="show-more">${ui.showAllExercises?'Mostra meno':'Mostra tutti gli esercizi ('+ranked.length+')'}</button>`:''}
<p class="footnote">Il volume è una misura di lavoro (kg × ripetizioni), non della forza pura; per i manubri vengono contati entrambi. Confronta preferibilmente lo stesso esercizio nel tempo.</p>`;}
function exerciseProgress(){const e=uniqueExercises().find(x=>C.exerciseKey(x)===ui.exerciseKey);if(!e)return progressPage();const s=C.series(db.history,ui.exerciseKey);const max=s.length?Math.max(...s.map(a=>a.weight)):0;const last=s.at(-1);const first=s[0];const rec=C.recommendation(e,db.history);
return `<div class="row spaced"><p class="eyebrow">EVOLUZIONE DELL'ESERCIZIO</p><button class="btn-link" data-action="navigate" data-page="progress">← Progressi</button></div><div class="row" style="align-items:flex-start;margin-bottom:18px">${pict(e,'thumb-lg')}<div class="grow"><h1 class="page-title" style="font-size:27px;margin-bottom:6px">${esc(e.name)}</h1><div class="tiny muted">${esc(e.group)} · ${esc(labelSeries(e))}</div></div></div><div class="stats-grid">${stat('Sedute',s.length)}${stat('Miglior carico',C.fmt(max),e.loadLabel||'kg')}${stat('Ultimo carico',C.fmt(last?.weight||0),e.loadLabel||'kg')}${stat('Differenza iniziale',s.length>1?(last.weight-first.weight>=0?'+':'')+C.fmt(last.weight-first.weight):'—','kg')}</div>
<div class="section-head"><h2 class="section-title">Carico massimo per seduta</h2></div><div class="card chart-panel">${chartLine(s)}<div class="chart-note">Kg massimi di una singola serie completata</div></div>
<div class="section-head"><h2 class="section-title">Coach progressivo</h2></div><div class="recommendation ${rec.type==='hold'?'warn':''}"><p><strong>${rec.type==='increase'?'↗ Aumento possibile. ':''}</strong>${esc(rec.text)}</p></div><div class="section-head"><h2 class="section-title">Ultime registrazioni</h2></div><div class="stack">${s.slice(-8).reverse().map(v=>`<div class="card row spaced"><div><strong class="small">${shortDate(v.date)}</strong><div class="tiny muted">${v.sets} serie · ${v.reps} ripetizioni totali</div></div><strong>${C.fmt(v.weight)} ${esc(e.loadLabel||'kg')}</strong></div>`).join('')||empty('Nessuna registrazione: questo grafico crescerà con i tuoi allenamenti.')}</div><p class="footnote">La progressione è un suggerimento, non una prescrizione: aumenta solo se movimento, recupero e attrezzatura lo consentono.</p>`;}
function settingsPage(){const size=new Blob([JSON.stringify(db)]).size;return `<p class="eyebrow">CONTROLLO DEI DATI</p><h1 class="page-title">Impostazioni.</h1><p class="subtitle">Il diario appartiene a te, anche quando non c’è connessione.</p><div class="card"><div class="settings-block"><div style="font-size:25px">↓</div><div class="grow"><strong>Esporta backup JSON</strong><p>Scarica tutte le schede, le sessioni e la seduta in corso (${C.fmt(Math.round(size/1024))} KB circa).</p><button class="btn btn-primary btn-sm" style="margin-top:12px" data-action="export">Scarica backup</button></div></div>
<div class="settings-block"><div style="font-size:25px">↑</div><div class="grow"><strong>Ripristina backup JSON</strong><p>Sostituisce i dati attuali con quelli contenuti nel file. Esporta prima un backup!</p><button class="btn btn-outline btn-sm" style="margin-top:12px" data-action="import">Scegli un file</button><input type="file" id="import-file" accept="application/json,.json" class="hidden"></div></div>
<div class="settings-block"><div style="font-size:25px">⌂</div><div class="grow"><strong>Installazione su iPhone</strong><p>Apri questo sito in Safari, premi Condividi e scegli “Aggiungi alla schermata Home”. Funziona anche senza Internet dopo il primo caricamento.</p></div></div>
<div class="settings-block"><div style="font-size:25px">♧</div><div class="grow"><strong>Salvataggio e privacy</strong><p>Dati e foto caricate rimangono nella memoria di questo browser. Nessun account e nessun server: senza backup potresti perdere tutto cancellando i dati di Safari o cambiando telefono.</p></div></div></div>
<div style="margin-top:18px"><button class="btn btn-danger btn-full" data-action="reset">Azzera tutti i dati</button></div><p class="footnote">Forge Gym 1.0 · Nessuna sincronizzazione tra dispositivi · Progressione indicativa, da adeguare alle condizioni individuali.</p>`;}
function showModal(title,content){ui.modal=`<div class="modal-backdrop" data-backdrop="true"><section class="modal-panel" role="dialog" aria-modal="true" aria-label="${esc(title)}"><div class="modal-top"><h2>${esc(title)}</h2><button class="icon-button" data-action="close-modal" aria-label="Chiudi">✕</button></div>${content}</section></div>`;renderModal();}
function renderModal(){document.getElementById('modal-root').innerHTML=ui.modal;}
function closeModal(){ui.modal='';ui.pendingImage='';renderModal();}
function planModal(id){const p=id?plan(id):null;showModal(p?'Modifica scheda':'Nuova scheda',`<form id="plan-form" data-id="${esc(p?.id||'')}"><div class="form-grid"><div class="form-field span2"><label for="plan-name">Nome scheda</label><input id="plan-name" name="name" maxlength="60" required placeholder="Es. Giorno 3 — Gambe" value="${esc(p?.name||'')}"></div><div class="form-field span2"><label for="plan-desc">Descrizione breve</label><textarea id="plan-desc" name="description" rows="2" maxlength="240" placeholder="Obiettivo, note...">${esc(p?.description||'')}</textarea></div></div><div class="form-actions"><button type="button" class="btn btn-outline" data-action="close-modal">Annulla</button><button class="btn btn-primary" type="submit">${p?'Salva':'Crea'}</button></div></form>`);}
function libraryModal(){const list=Object.values(catalog);showModal('Libreria esercizi',`<p class="subtitle">Aggiungi un esercizio alla scheda selezionata; potrai personalizzarlo dopo.</p><div class="library-picker">${list.map(e=>`<button class="library-option" data-action="add-library" data-key="${esc(e.key)}">${pict(e,'thumb-sm')}<div class="grow"><strong>${esc(e.name)}</strong><br><small>${esc(e.group)} · ${esc(labelSeries(e))}</small></div><span class="arrow">＋</span></button>`).join('')}</div>`);}
function exerciseModal(id){const p=plan(ui.planId);const e=id?p?.exercises.find(x=>x.id===id):null;ui.pendingImage='';const kind=e?.kind||'strength';const ranges=(e?.sets||[{min:6,max:8},{min:6,max:8},{min:6,max:8}]).map(s=>`${s.min}-${s.max}`).join(', ');
showModal(e?'Modifica esercizio':'Nuovo esercizio',`<form id="exercise-form" data-id="${esc(e?.id||'')}"><div class="form-grid"><div class="form-field span2"><label for="ex-name">Nome *</label><input id="ex-name" name="name" required maxlength="100" placeholder="Es. Rematore manubrio" value="${esc(e?.name||'')}"></div>
<div class="form-field"><label for="ex-group">Gruppo muscolare</label><input id="ex-group" name="group" maxlength="60" placeholder="Dorsali" value="${esc(e?.group||'')}" required></div><div class="form-field"><label for="ex-kind">Tipo</label><select id="ex-kind" name="kind"><option value="strength" ${kind==='strength'?'selected':''}>Pesi / Serie</option><option value="time" ${kind==='time'?'selected':''}>Durata (minuti)</option><option value="activity" ${kind==='activity'?'selected':''}>Attività / Stretching</option></select></div>
<div class="form-field span2"><label for="ex-description">Descrizione esecuzione</label><textarea id="ex-description" name="description" rows="3" maxlength="1000" placeholder="Come si esegue...">${esc(e?.description||'')}</textarea></div>
<div class="form-field span2"><label for="ex-targets">Serie e intervalli di ripetizioni</label><input id="ex-targets" name="targets" placeholder="6-8, 6-8, 6-8" value="${esc(ranges)}"><div class="form-hint">Una coppia per serie: “6-8, 6-8, 6-8” = 3 serie. Per 1×6/8 e 1×8/10 scrivi “6-8, 8-10”. Ignorato per attività e minuti.</div></div>
<div class="form-field"><label>Recupero (secondi)</label><input name="rest" type="number" min="0" max="1800" step="15" value="${e?.rest??120}"></div><div class="form-field"><label>Aumento suggerito (kg)</label><select name="step"><option value="2.5" ${(e?.step??2.5)===2.5?'selected':''}>2,5 kg</option><option value="5" ${e?.step===5?'selected':''}>5 kg</option><option value="1" ${e?.step===1?'selected':''}>1 kg</option><option value="0.5" ${e?.step===.5?'selected':''}>0,5 kg</option></select></div>
<div class="form-field"><label>Unità del carico</label><select name="loadLabel"><option value="kg" ${e?.loadLabel!=='kg/manubrio'?'selected':''}>kg totali / macchina</option><option value="kg/manubrio" ${e?.loadLabel==='kg/manubrio'?'selected':''}>kg per manubrio</option></select></div><div class="form-field"><label>Minuti (per cardio)</label><input name="minutes" type="number" min="0" max="600" value="${e?.minutes||8}"></div>
<div class="form-field span2"><label>Immagine (facoltativa)</label><input name="image" type="url" placeholder="https://..." value="${e?.image?.startsWith('https:')?esc(e.image):''}"><div class="form-hint">Puoi lasciare l’immagine originale, inserire un URL HTTPS o caricare una foto qui sotto.</div><input id="exercise-image-file" type="file" accept="image/jpeg,image/png,image/webp"><div id="uploaded-img-msg" class="form-hint"></div></div></div>
<div class="form-actions"><button class="btn btn-outline" type="button" data-action="close-modal">Annulla</button><button class="btn btn-primary" type="submit">Salva esercizio</button></div>${e?`<button type="button" class="btn btn-danger btn-full" style="margin-top:12px" data-action="remove-ex" data-id="${esc(e.id)}">Rimuovi dalla scheda</button>`:''}</form>`);}
function parseTargets(text){const chunks=String(text).split(/[,;\n]+/).map(s=>s.trim()).filter(Boolean);if(!chunks.length||chunks.length>20)throw Error('Inserisci da 1 a 20 coppie di ripetizioni.');return chunks.map(s=>{const m=s.match(/^(\d+)\s*[-/–]\s*(\d+)$/);if(!m)throw Error('Formato non valido. Usa ad esempio 6-8, 6-8, 8-10.');let min=Number(m[1]),max=Number(m[2]);if(min<1||max>100||min>max)throw Error('Ripetizioni non valide.');return {min,max};});}
async function processImage(file){if(!file||!/^image\/(png|jpeg|webp)$/.test(file.type))throw Error('Carica un’immagine JPG, PNG o WebP.');if(file.size>10e6)throw Error('Immagine troppo grande (massimo 10 MB).');const url=URL.createObjectURL(file);try{const im=new Image();await new Promise((res,rej)=>{im.onload=res;im.onerror=rej;im.src=url;});const ratio=Math.min(1,420/Math.max(im.width,im.height)),canvas=document.createElement('canvas');canvas.width=Math.round(im.width*ratio);canvas.height=Math.round(im.height*ratio);canvas.getContext('2d').drawImage(im,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.70);}finally{URL.revokeObjectURL(url);}}
function sessionEntry(id){return db.active?.entries.find(e=>e.id===id);}
function moveEx(id,dir){let p=plan(ui.planId);if(!p)return;const i=p.exercises.findIndex(e=>e.id===id);if(i<0||i+dir<0||i+dir>=p.exercises.length)return;[p.exercises[i],p.exercises[i+dir]]=[p.exercises[i+dir],p.exercises[i]];persist();render();}
function mutateSet(eid,index,fn){const e=sessionEntry(eid),s=e?.sets?.[Number(index)];if(!s)return;fn(s,e);persist();render();}
function maybeRest(e){if(!e.rest||e.rest<1)return;ui.restUntil=Date.now()+e.rest*1000;updateTimer();}
function updateTimer(){const el=document.getElementById('timer-banner'),clock=document.getElementById('timer-count');if(!el||!clock)return;let diff=Math.max(0,Math.ceil((ui.restUntil-Date.now())/1000));el.classList.toggle('hidden',diff<=0);clock.textContent=`${Math.floor(diff/60)}:${String(diff%60).padStart(2,'0')}`;}
setInterval(updateTimer,1000);
function route(page){ui.page=page;if(page==='session'&&!ui.openExerciseId)ui.openExerciseId=db.active?.entries[0]?.id||null;render();window.scrollTo(0,0);}
function exportJson(){const blob=new Blob([JSON.stringify({...db,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`forge-gym-backup-${new Date().toISOString().slice(0,10)}.json`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('Backup preparato: salvalo in File o iCloud.');}
function guardImport(obj){if(!obj||obj.version!==1||!Array.isArray(obj.plans)||!Array.isArray(obj.history)||obj.plans.length>100||obj.history.length>10000)throw Error('File non compatibile con Forge Gym.');for(const p of obj.plans){if(typeof p.id!=='string'||typeof p.name!=='string'||!Array.isArray(p.exercises)||p.exercises.length>200)throw Error('Schede non valide.');}for(const h of obj.history){if(!Array.isArray(h.entries)||typeof h.id!=='string')throw Error('Storico non valido.');}if(obj.active&&(!Array.isArray(obj.active.entries)||typeof obj.active.id!=='string'))throw Error('Seduta attiva non valida.');return {version:1,plans:obj.plans,history:obj.history,active:obj.active||null};}
function confirmAction(msg){return window.confirm(msg);}
document.addEventListener('click',ev=>{const btn=ev.target.closest('[data-action]');if(!btn){if(ev.target.matches('[data-backdrop]'))closeModal();return;}const a=btn.dataset.action,id=btn.dataset.id,index=btn.dataset.index,key=btn.dataset.key;
switch(a){
case 'navigate':closeModal();route(btn.dataset.page);break;
case 'go-plan':ui.planId=id||db.plans[0]?.id;route('plan');break;
case 'create-plan-modal':planModal();break;
case 'edit-plan-modal':planModal(id);break;
case 'close-modal':closeModal();break;
case 'library-modal':libraryModal();break;
case 'custom-ex-modal':exerciseModal(null);break;
case 'edit-ex-modal':exerciseModal(id);break;
case 'add-library':{let p=plan(ui.planId);if(!p||!catalog[key])return;p.exercises.push(cloneExercise(key));closeModal();persist();render();toast('Esercizio aggiunto alla scheda.');break;}
case 'move-ex':moveEx(id,Number(btn.dataset.dir));break;
case 'remove-ex':{const p=plan(ui.planId);if(!p||!confirmAction('Vuoi rimuovere questo esercizio dalla scheda?'))return;p.exercises=p.exercises.filter(e=>e.id!==id);closeModal();persist();render();break;}
case 'duplicate-plan':{const p=plan(id);if(!p)return;const copy=structuredClone(p);copy.id=uid();copy.name+=' (copia)';copy.exercises.forEach(e=>e.id=uid());db.plans.push(copy);ui.planId=copy.id;persist();render();toast('Scheda duplicata.');break;}
case 'delete-plan':{if(db.active?.planId===id){toast('Termina prima la seduta in corso.');return;}if(!confirmAction('Eliminare la scheda? Le sedute nello storico restano disponibili.'))return;db.plans=db.plans.filter(p=>p.id!==id);ui.planId=db.plans[0]?.id||'';persist();route('plans');break;}
case 'start':start(id);break;
case 'toggle-ex':ui.openExerciseId=ui.openExerciseId===id?null:id;render();break;
case 'cancel-session':if(confirmAction('Annullare questa seduta? Le serie NON verranno salvate nello storico.')){db.active=null;ui.restUntil=0;persist();route('plans');}break;
case 'set-done':mutateSet(btn.dataset.eid,index,(s,e)=>{s.done=!s.done;if(s.done)maybeRest(e);});break;
case 'set-reps':mutateSet(btn.dataset.eid,index,s=>s.reps=Number(btn.dataset.value));break;
case 'weight-step':mutateSet(btn.dataset.eid,index,(s,e)=>{const amount=Number(e.step)||2.5;s.kg=Math.max(0,Math.round((Number(s.kg||0)+amount*Number(btn.dataset.dir))*100)/100);});break;
case 'activity-done':{const e=sessionEntry(id);if(e){e.done=!e.done;persist();render();}break;}
case 'apply-step':{const e=sessionEntry(id),r=e?C.recommendation(e,db.history):null;if(!e||r?.type!=='increase')return;const prev=C.lastExercise(db.history,C.exerciseKey(e));e.sets.forEach((s,i)=>{const prevkg=Number(prev?.sets?.[i]?.kg)||0;if(prevkg>0)s.kg=Math.round((prevkg+r.step)*100)/100;});persist();render();toast('Carichi suggeriti applicati: verifica gli incrementi reali della macchina.');break;}
case 'finish':finish();break;
case 'stop-timer':ui.restUntil=0;updateTimer();break;
case 'history-filter':ui.historyFilter=btn.dataset.value;render();break;
case 'history-detail':ui.historyId=id;route('history-detail');break;
case 'delete-history':if(confirmAction('Eliminare definitivamente questa seduta dallo storico?')){db.history=db.history.filter(h=>h.id!==id);persist();route('history');}break;
case 'progress-metric':ui.progressMetric=btn.dataset.value;render();break;
case 'exercise-insights':ui.exerciseKey=key;closeModal();route('exercise-progress');break;
case 'show-more':ui.showAllExercises=!ui.showAllExercises;render();break;
case 'export':exportJson();break;
case 'import':document.getElementById('import-file')?.click();break;
case 'reset':if(confirmAction('ATTENZIONE: cancellerai schede, storico e seduta in corso. Hai esportato il backup?')&&confirmAction('Ultima conferma: vuoi davvero cancellare TUTTI i dati locali?')){db=defaultDb();persist();ui.page='home';ui.planId=db.plans[0]?.id;render();toast('Dati ripristinati allo stato iniziale.');}break;
}});
document.addEventListener('change',async ev=>{const t=ev.target;
if(t.id==='exercise-image-file'&&t.files?.[0]){try{ui.pendingImage=await processImage(t.files[0]);const label=document.getElementById('uploaded-img-msg');if(label)label.textContent='✓ Immagine caricata e ridimensionata sul dispositivo.';}catch(err){toast(err.message);}return;}
if(t.id==='import-file'&&t.files?.[0]){try{const content=await t.files[0].text();const parsed=guardImport(JSON.parse(content));if(!confirmAction(`Ripristinare ${parsed.plans.length} schede e ${parsed.history.length} sedute? I dati attuali saranno sostituiti.`))return;db=parsed;persist();ui.planId=db.plans[0]?.id||'';ui.openExerciseId=null;route(db.active?'session':'home');toast('Backup ripristinato.');}catch(err){toast('Importazione fallita: '+err.message);}finally{t.value='';}return;}
if(t.dataset.field){const e=sessionEntry(t.dataset.eid);if(!e)return;const val=Number(String(t.value).replace(',','.'));if(!Number.isFinite(val)||val<0||val>2000){toast('Inserisci un numero valido.');t.value=t.dataset.field==='kg'?String(e.sets?.[Number(t.dataset.index)]?.kg||0):String(e.minutes||0);return;}if(t.dataset.field==='kg'){const s=e.sets?.[Number(t.dataset.index)];if(s)s.kg=Math.round(val*100)/100;}else if(t.dataset.field==='minutes'){e.minutes=Math.round(val);}persist();}
});
document.addEventListener('input',ev=>{const t=ev.target;if(!t.dataset.field||!t.value.trim())return;const e=sessionEntry(t.dataset.eid);if(!e)return;const val=Number(String(t.value).replace(',','.'));if(!Number.isFinite(val)||val<0||val>2000)return;if(t.dataset.field==='kg'){const s=e.sets?.[Number(t.dataset.index)];if(s)s.kg=Math.round(val*100)/100;}else if(t.dataset.field==='minutes'){e.minutes=Math.round(val);}persist();});
document.addEventListener('submit',ev=>{const form=ev.target;if(form.id==='plan-form'){ev.preventDefault();const fd=new FormData(form),name=String(fd.get('name')||'').trim(),description=String(fd.get('description')||'').trim();if(!name){toast('Inserisci un nome.');return;}let id=form.dataset.id;if(id){let p=plan(id);if(!p)return;p.name=name;p.description=description;}else{const p={id:uid(),name,description,exercises:[]};db.plans.push(p);ui.planId=p.id;}closeModal();persist();route('plan');toast('Scheda salvata.');}
if(form.id==='exercise-form'){ev.preventDefault();const fd=new FormData(form),kind=String(fd.get('kind')),name=String(fd.get('name')||'').trim(),group=String(fd.get('group')||'').trim();if(!name||!group)return toast('Inserisci nome e gruppo.');let targets=[];try{targets=kind==='strength'?parseTargets(fd.get('targets')):[];}catch(err){toast(err.message);return;}
const p=plan(ui.planId);if(!p)return;let exercise=form.dataset.id?p.exercises.find(e=>e.id===form.dataset.id):null;const remote=String(fd.get('image')||'').trim();const image=ui.pendingImage||(remote.startsWith('https://')?remote:'')||exercise?.image||'';
const values={name,group,description:String(fd.get('description')||'').trim(),kind,sets:targets,rest:Math.min(1800,Math.max(0,Number(fd.get('rest'))||0)),step:Number(fd.get('step'))||2.5,minutes:Math.max(0,Number(fd.get('minutes'))||0),loadLabel:String(fd.get('loadLabel'))==='kg/manubrio'?'kg/manubrio':'kg',image};
if(exercise){Object.assign(exercise,values);}else{p.exercises.push({id:uid(),key:uid(),...values});}
closeModal();persist();render();toast('Esercizio salvato.');}
});
document.addEventListener('keydown',ev=>{if(ev.key==='Escape'&&ui.modal)closeModal();});
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(e=>console.warn('Offline non disponibile',e)));
render();
})();
